# Generated by Django 4.2 on 2023-04-28 09:34

from django.db import migrations


def fix_employee_ids(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    employees = Employee.objects.all()
    for i, employee in enumerate(employees):
        employee.id = i + 1
        employee.save()


class Migration(migrations.Migration):
    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fix_employee_ids),
    ]
