# Generated by Django 4.2 on 2023-04-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_auto_20230428_0934"),
    ]

    operations = []
